server:
  port: 9861
eureka:
    client:
        service-url:
            defaultZone: http://localhost:8761/eureka/
spring:
  application:
        name: micro-service2
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest